version: '3'
services:
  code-robot-cli-redis:
    image: redis
    container_name: code-robot-cli-redis
    ports:
      - 6380:6379
  code-robot-cli-server:
    image: registry.cn-qingdao.aliyuncs.com/greedcat/code-robot-cli-server:{{tag}}
    container_name: code-robot-cli-server
    ports:
      - 7004:7003
